services:
  app:
    restart: unless-stopped
    networks:
      - baphomet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
      - '443:443'
    volumes:
      - ./src:/usr/src/app/src
      - ../baphomet-ui/dist:/usr/src/app/dist
    environment:
      - ATLAS_DB_PASSWORD=${ATLAS_DB_PASSWORD}
      - ATLAS_DB_USERNAME=${ATLAS_DB_USERNAME}
      - ATLAS_CLUSTER=${ATLAS_CLUSTER}
      - ATLAS_DB=${ATLAS_DB}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}

networks:
  baphomet:
    external: true