name: Deploy Baphomet Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create .env File
        run: |
          echo "ATLAS_DB_PASSWORD=${{ secrets.ATLAS_DB_PASSWORD }}" >> .env
          echo "ATLAS_DB_USERNAME=${{ secrets.ATLAS_DB_USERNAME }}" >> .env
          echo "ATLAS_CLUSTER=${{ secrets.ATLAS_CLUSTER }}" >> .env
          echo "ATLAS_DB=${{ secrets.ATLAS_DB }}" >> .env
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build and Push Docker Images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Image from Docker Hub
        run: docker-compose -f docker-compose.yml pull

      - name: Delete Old Container
        run: docker rm -f baphomet-server-container

      - name: Run Docker Container
        run: docker-compose -f docker-compose.yml up -d
 